apiVersion: apps/v1              #Este archivo .yaml configura el deploy
kind: Deployment
metadata:
  name: next1-d
  labels:
    app: next1
spec: #especificaciones del deploy
  replicas: 2
  selector:
    matchLabels:
      app: next1
  template:  
    metadata:
      labels: 
        app: next1
    spec: #especificaciones del pod
      containers:
        - name: next1
          image: adrianrcv/hlc:6.0
          ports:
            - containerPort: 80
            - containerPort: 3000
          env:
          - name: GITHUB
            value: "https://github.com/AdrianRCV/PokeAPINext.git"
          - name: USUARIO
            value: "adrian"
          - name: PASSWD
            value: "adrian"
          - name: HOSTNAME
            value: "nextpokeapi"
          - name: PORT_SSH
            value: "45678"
          - name: TZ
            value: "Europe/Madrid"
      