apiVersion: v1
kind: Service
metadata:
  name: next-s
  labels:
    app: next
spec:
  selector:
    app: next
  type:  LoadBalancer
  ports:
  - name:  http-port
    protocol: TCP
    port:  8087
    targetPort:  80
    