apiVersion: v1
kind: Service
metadata:
  name: react-s
  labels:
    app: react
spec:
  selector:
    app: react
  type:  LoadBalancer
  ports:
  - name:  http-port
    protocol: TCP
    port:  8089
    targetPort:  80