apiVersion: v1
kind: Pod
metadata:
 name: react1
 labels:
  app: react
spec:
  containers:
  - name: react
    image: adrianrcv/hlc:3.0
    ports:
    - containerPort: 80  
    - containerPort: 3000
    env:
    - name: GITHUB
      value: "https://github.com/AdrianRCV/PokeAPI-HLC.git"
    - name: USUARIO
      value: "adrian"
    - name: PASSWD
      value: "adrian"
    - name: HOSTNAME
      value: "pokeapi"
    - name: PORT_SSH
      value: "45678"
    - name: TZ
      value: "Europe/Madrid"