apiVersion: v1     #Este archivo .yaml configura el servicio
kind: Pod
metadata:
  name: nginx3
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: nginx
      image: adrianrcv/hlc:4.0
      envFrom:
        - configMapRef: 
            name: app-env
