apiVersion: v1
kind: Service
metadata:
  name: webcv-s
  labels:
    app: webcv
spec:
  selector:
    app: webcv
  type:  NodePort
  ports:
  - name:  http-port
    protocol: TCP
    port:  80
    targetPort:  80
    nodePort: 30080